name: flutter_pomodoro
description: "Pomodoro Timer"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/working.mp3
    - assets/sounds/break.mp3
    - assets/sounds/rest.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pomodoro-icon.png"
  adaptive_icon_background: "#ffffff"
